### ISSUE TITLE
Clock Town Scrub leaving cutscene

### ISSUE THREAD

**Issue by LittleCube-hax** [LittleCube-hax/MMRecompRando#24]
Skip sell_nuts leaving with Moon's Tear cutscene.

**Comment by G4M3RL1F3** [comment]
As of mod release v0.2.4, only the beginning of the cutscene is skipped. A few seconds after the scrub leaves the flower, the game goes into a cutscene, following him until he leaves.

**Comment by LittleCube-hax** [comment]
Just got it as well.

**Comment by LittleCube-hax** [comment]
Just fixed.
