### ISSUE TITLE
Freecam: Climbing a ledge prevents turning the camera

### ISSUE THREAD

**Issue by G4M3RL1F3** [LittleCube-hax/MMRecompRando#25]
During the animation of climbing a ledge, the camera refuses to turn when using the right stick. It is a bit annoying when trying to get the North Clock Town Piece of Heart especially when the camera auto-pans behind Link (because yes, that can also happen), making jumps harder.

**Comment by LittleCube-hax** [comment]
Fixed with new version of z-target-fixes, will package in next release.
