### ISSUE TITLE
Goron Treasure Game Gives Multiple Checks

### ISSUE THREAD

**Issue by ThatHypedPerson** [LittleCube-hax/MMRecompRando#29]
I was playing through [this seed](https://github.com/user-attachments/files/17641306/AP_61609854590989682552.zip) and got both the expected `East Clock Town Treasure Game Chest (Goron)` reward and `North Clock Town Great Fairy Reward (Has Transformation Mask)`.

This does not appear to happen on another seed I generated though, so I'm not sure how it may happen. It is reproducible on the seed I have sent though (Slot Name: `Hyped`) for further testing.

**Comment by LittleCube-hax** [comment]
Thanks for the report! It was because the item itself is the Great Fairy Mask, which normally triggers that check if the game gives it to you.

It's fixed now though, so I'll close this.
