### ISSUE TITLE
Town Shooting Gallery is borked

### ISSUE THREAD

**Issue by ThatHypedPerson** [LittleCube-hax/MMRecompRando#37]
Getting perfect in Town Archery will now give you 100 points, no longer giving the 50 point reward. However doing nothing will get a proper perfect will actually give the perfect reward.
![image](https://github.com/user-attachments/assets/ac166c07-58f5-4d1a-9a32-22462b543c1f)
###### (just remove line 220 in `shooting_gallery_hooks.c` and its fixed)

**Comment by LittleCube-hax** [comment]
Ah, I see I only removed half of my debug code (I must have done shooting gallery hundreds of times).

**Comment by LittleCube-hax** [comment]
That should do it.
