### ISSUE TITLE
Linux (SteamDeck) Connecting to AP but not Tracking

### ISSUE THREAD

**Issue by GFreak01** [LittleCube-hax/MMRecompRando#40]
Once I get into the game, all items are "AP Item", I have no sword, and the AP server does not show any checks being completed.

v2.3e works, however I've tried v2.4, v2.5, and v2.5a.  All 3 newer versions have this issue.

I've tried both localhost and AP servers.  The server is communicating with the client, allowing connection and disconnection messages to match opening and closing ZeldaRecompile.

Attached is stdout of Zelda Recompile program, while using v2.5a, showing that it authenticates with the AP server.  
The stdout when using **v2.3e** has the same output, however it then continues with additional lines. (e.g. box type is 5, item type is 1)

[ZeldaRecompile Stdout.txt](https://github.com/user-attachments/files/17690195/ZeldaRecompile.Stdout.txt)

**Comment by LittleCube-hax** [comment]
Have you generated using the newer .apworld file provided with the mod releases of those versions?

**Comment by GFreak01** [comment]
I verified that I was changing the apworld file with each release attempted.

However, I just tested the newest 2.5b release and everything is working!
