### ISSUE TITLE
Add Option to Shuffle Hero Shield

### ISSUE THREAD

**Issue by ThatHypedPerson** [LittleCube-hax/MMRecompRando#43]
Since the starting sword has the option to be shuffled, why not also shuffle the starting shield?

I don't believe any check in the game explicitly requires Hero Shield (at least none of the ones currently implemented), so it wouldn't be too much to implement.

**Comment by LittleCube-hax** [comment]
Yeah we can try it, as well as options for shuffling beginning hearts.

**Comment by LittleCube-hax** [comment]
The shield, as well as 8 of Link's beginning heart pieces can be shuffled.
