### ISSUE TITLE
East Clock Town Shooting Gallery double reward

### ISSUE THREAD

**Issue by G4M3RL1F3** [LittleCube-hax/MMRecompRando#6]
Currently, the East Clock Town Shooting Gallery must be played twice to get both rewards. The minigame itself is a bit lengthy, so I suggest the following: if the player scores 50, both rewards get sent.

**Comment by LittlestCube** [comment]
Totally forgot about this (again) tyvm 😋

**Comment by LittleCube-hax** [comment]
Link will now get both items and play the get item animation for each.
